services:
  - type: web
    name: nexus-projetos
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
